version: "3.8"

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5674:5672"
      - "15674:15672"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
