version: "3.8"

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
